### ISSUE TITLE
Autofix breaks functionality ('==' is changed to 'is')

### ISSUE THREAD

**Issue by akanz1** [charliermarsh/ruff#1869]
For certain cases with e.g. pandas the autofix functionality causes undesirable changes as something along the lines of

`ser.loc[ser == False]` gets changed to `ser.loc[ser is False]`.

I haven't observed it yet, but i'm also aware of cases using SQLAlchemy where `==` is required and `is` does not work.

```python
import pandas as pd
ser = pd.Series({"a":True, 'b':False, 'c':True}, dtype='bool')
ser.loc[ser == False]
```

![image](https://user-images.githubusercontent.com/51492342/212464419-78785756-309a-46fa-9ab8-4a0d59ef39bc.png)

After autofix the functionality is broken
```bash
>>> ser.loc[ser is False]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akanz/mambaforge/envs/.../lib/python3.8/site-packages/pandas/core/indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/akanz/mambaforge/envs/.../lib/python3.8/site-packages/pandas/core/indexing.py", line 1201, in _getitem_axis
    self._validate_key(key, axis)
  File "/Users/akanz/mambaforge/envs/.../lib/python3.8/site-packages/pandas/core/indexing.py", line 1011, in _validate_key
    raise KeyError(
KeyError: 'False: boolean label can not be used without a boolean index'
```

See also #1852

**Comment by akanz1** [comment]
closing in favor of #1852
