### ISSUE TITLE
Ruff rewrites `Union[tuple_of_types]` in potentially breaking ways

### ISSUE THREAD

**Issue by rouge8** [charliermarsh/ruff#3215]
After Ruff rewrites this file, Python starts throwing an error.

## `t.py`

```python
from typing import Union, cast


def _make_optional(cls: type) -> type:
    """Convert a type to an Optional type."""
    return cast(type, cls | None)


new_types = (int, float)

_make_optional(cast(type, Union[new_types]))
```

## output

```
❯ ruff --isolated --fix --target-version py311 --select UP t.py
Found 1 error (1 fixed, 0 remaining).
```

## rewritten

```python
from typing import Union, cast


def _make_optional(cls: type) -> type:
    """Convert a type to an Optional type."""
    return cast(type, cls | None)


new_types = (int, float)

_make_optional(cast(type, new_types))
```

Unfortunately, `t.py` now errors out:

```
Traceback (most recent call last):
  File "/Users/andyfreeland/t.py", line 11, in <module>
    _make_optional(cast(type, new_types))
  File "/Users/andyfreeland/t.py", line 6, in _make_optional
    return cast(type, cls | None)
                      ~~~~^~~~~~
TypeError: unsupported operand type(s) for |: 'tuple' and 'NoneType'
```

## version

```
ruff 0.0.252
```

**Comment by rouge8** [comment]
FWIW, `pyupgrade --py311-plus t.py` does not make any changes to the original `t.py`.

**Comment by charliermarsh** [comment]
Yeah `pyupgrade` never applies PEP 604 transformations to runtime types. Maybe we shouldn't either. It's come up before.

**Comment by charliermarsh** [comment]
This was another recent case: #2981.

**Comment by charliermarsh** [comment]
(So let's just change it.)
