### ISSUE TITLE
`CONTRIBUTING.md` `MkDocs` incomplete: adding that `cargo` is required

### ISSUE THREAD

**Issue by jamesbraza** [charliermarsh/ruff#4719]
I was trying to follow the `MkDocs` section of `CONTRIBUTING.md`: https://github.com/charliermarsh/ruff/blob/main/CONTRIBUTING.md#mkdocs

On a clean machine without `cargo`, after making a new Python 3.10.11 `venv`:

```sh
> pip install -r docs/requirements.txt
> python scripts/generate_mkdocs.py
Traceback (most recent call last):
  File "/path/to/ruff/scripts/generate_mkdocs.py", line 161, in <module>
    main()
  File "/path/to/ruff/scripts/generate_mkdocs.py", line 86, in main
    subprocess.run(["cargo", "dev", "generate-docs"], check=True)
  File "/path/to/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/path/to/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/path/to/.pyenv/versions/3.10.11/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'
```

After installing Rust:
1. `brew install rustup && rustup-init`
2. Entering `1` for normal install
3. Restarting my terminal

I was able to run `python scripts/generate_mkdocs.py` and then `mkdocs serve`.

The request: having the `MkDocs` section mention a Rust installation is required

**Comment by jamesbraza** [comment]
Thanks @charliermarsh for your dedication!
